version: '2'
services:
  weston:
    build:
      context: ./weston
      dockerfile: ubuntu.Dockerfile

    ports:
      - "3389:3389"
      - "10000:10000"

    # depends_on:
      # - novnc
    networks:
      - x11


    
#   novnc:
#     image: theasp/novnc:latest
#     environment:
#       # Adjust to your screen size
#       - DISPLAY_WIDTH=1600
#       - DISPLAY_HEIGHT=968
#       - RUN_XTERM=no
#     ports:
#       - "8080:8080"
#     networks:
#       - x11
networks:
  x11: